<table class="table table-condensed table-bordered fit">
  <tbody>
    <tr>
      <td><b>CPU</td>
      <td>{{$item->spec->cpu}}</td>
      <td><b>LAN</td>
      <td>{{$item->spec->lan}}</td>
    </tr>
    <tr>
      <td><b>RAM</td>
      <td>{{$item->spec->ram}}</td>
      <td><b>WLAN</td>
      <td>{{$item->spec->wlan}}</td>
    </tr>
    <tr>
      <td><b>HDD</td>
      <td>{{$item->spec->hdd}}</td>
      <td><b>OS</td>
      <td>{{$item->spec->os}}</td>
    </tr>
    <tr>
      <td><b>ODD</td>
      <td>{{$item->spec->odd}}</td>
      <td><b>PSU</td>
      <td>{{$item->spec->psu}}</td>
    </tr>
    <tr>
      <td><b>GPU</td>
      <td>{{$item->spec->gpu}}</td>
      <td><b>Screen Size</td>
      <td>{{$item->spec->screen_size}}</td>
    </tr>
    <tr>
      <td><b>Battery</td>
      <td>{{$item->spec->battery}}</td>
      <td><b>Screen Resolution</td>
      <td>{{$item->spec->screen_rez}}</td>
    </tr>
    <tr>
      <td><b>USB</td>
      <td>{{$item->spec->usb}}</td>
    </tr>
  </tbody>
</table>
